# Development environment overrides
environment: dev

image:
  repository: harbor.server.thweb.click/boardgame-devsecops/app
  tag: latest  # Jenkins will update this
  pullPolicy: Always

replicaCount: 1

resources:
  limits:
    cpu: 400m
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 128Mi

ingress:
  enabled: true
  className: nginx
  host: boardgame-dev.app.thweb.click
  tls:
    enabled: false  # No SSL for dev (faster iteration)
  annotations: {}

env:
  springH2ConsoleEnabled: "true"
